const WEEKDAYS = ["周日", "周一", "周二", "周三", "周四", "周五", "周六"];
const { dateAfter } = require("./dateUtils.js");

function weekdayAfter(days) {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return WEEKDAYS[date.getDay()];
}

function monthDayWeekAfter(days) {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return `${date.getMonth() + 1}月${date.getDate()}日 ${WEEKDAYS[date.getDay()]}`;
}

function makeCoupon(data) {
  const days = typeof data.expireOffsetDays === "number" ? data.expireOffsetDays : 3;
  const isPast = days < 0;
  const isUsed = data.statusCode === "used";
  const defaultState = isUsed ? "已使用" : (isPast ? "已过期" : (days <= 1 ? "临期" : (days <= 5 ? "优先" : "可约")));
  const defaultStateClass = isUsed ? "used" : (isPast ? "expired" : (days <= 1 ? "urgent" : (days <= 5 ? "priority" : "ready")));
  const defaultStatus = isUsed ? "已使用" : (isPast ? "已过期" : "未安排");
  const defaultExpiresIn = isUsed ? "已使用" : (isPast ? `已过期${Math.abs(days)}天` : (days === 0 ? "今天过期" : (days === 1 ? "明天过期" : `${days}天后过期`)));

  return Object.assign({
    category: "food",
    people: "2人",
    platform: "美团",
    reservationRequired: false,
    expireDate: dateAfter(days),
    expiresIn: defaultExpiresIn,
    usableTime: "周一至周日 11:00-22:00",
    travelTime: "20分钟",
    recommendedAt: "近期",
    score: isPast ? 30 : 85,
    status: defaultStatus,
    state: defaultState,
    stateClass: defaultStateClass,
    usedAt: isUsed ? `${dateAfter(-7)} 12:30` : "",
    tags: [],
    reasons: [],
    reasonItems: [],
    notices: [],
    cleanup: "无需额外清洁时间",
  }, data);
}

const coupons = [
  makeCoupon({
    id: "c_thai_001",
    title: "曼谷街头泰式大排档3-4人聚餐",
    venue: "帕蓬泰味小馆",
    type: "泰餐",
    category: "food",
    people: "3-4人",
    platform: "大众点评",
    expireOffsetDays: 12,
    usableTime: "周一至周日 11:30-21:30",
    address: "华强北九方购物中心L4层",
    latitude: 22.5482,
    longitude: 114.0852,
    travelTime: "22分钟",
    recommendedAt: "本周六 晚市",
    score: 89,
    price: "198",
    originalPrice: "368",
    shortReason: "适合3-4人小聚，酸辣开胃，性价比极高",
    dishes: "泰式冬阴功海鲜汤1份、黄咖喱牛腩1份、泰式柠檬清蒸鱼1条、青木瓜沙拉1份、芒果糯米饭1份、泰式奶茶4杯",
    tags: ["聚餐优选", "酸辣开胃", "朋友小聚", "东南亚风味"],
    reasons: ["适合多位好友周末聚餐", "菜品丰富多样，人均仅50元", "无需提前繁琐预约"],
    reasonItems: [
      { label: "多人", title: "分量充足", desc: "4道硬菜搭配甜品饮料，完美满足3-4人小聚。" },
      { label: "风味", title: "酸辣解腻", desc: "经典冬阴功配咖喱，适合朋友周末欢聚。" },
    ],
    notices: ["周末就餐高峰期可能需要取号排队"],
    note: "咖喱牛腩拌饭绝配，柠檬鱼酸辣度可调微辣。",
  }),
  makeCoupon({
    id: "c_bistro_001",
    title: "精酿啤酒与意式窑炉披萨双人微醺套餐",
    venue: "HopCraft 啤酒工坊",
    type: "清吧",
    category: "play",
    people: "2人",
    platform: "美团",
    expireOffsetDays: 4,
    usableTime: "周一至周日 17:30-01:00",
    address: "车公庙十亩地街区B栋102",
    latitude: 22.5342,
    longitude: 114.0261,
    travelTime: "18分钟",
    recommendedAt: "周五 晚上",
    score: 91,
    price: "128",
    originalPrice: "238",
    shortReason: "周五夜间放松微醺首选，窑炉现烤披萨香脆",
    dishes: "经典玛格丽特披萨1份、黑松露帕尔马火腿披萨1份、精酿IPA/世涛生啤任选2杯、香炸粗薯1份",
    tags: ["微醺夜生活", "周五必选", "精酿生啤", "氛围感"],
    reasons: ["周五夜晚聚会绝佳场所", "4天后即将过期，需优先安排", "店内音乐氛围轻松自在"],
    reasonItems: [
      { label: "时段", title: "周五微醺夜", desc: "结束一周工作后的轻松社交好去处。" },
      { label: "临期", title: "4天后到期", desc: "建议本周五或周六晚间锁定使用。" },
    ],
    notices: ["仅限晚间与夜间时段核销"],
    note: "推荐柑橘香气IPA搭配黑松露披萨，口感层次丰富。",
  }),
  makeCoupon({
    id: "c_boardgame_001",
    title: "沉浸式剧本杀/桌游4人通兑畅玩4小时",
    venue: "次元立方·沉浸推理馆",
    type: "桌游",
    category: "play",
    people: "4人",
    platform: "抖音",
    expireOffsetDays: 18,
    usableTime: "周一至周日 13:00-23:00",
    address: "高新园大冲商务中心C座808",
    latitude: 22.5428,
    longitude: 113.9535,
    travelTime: "15分钟",
    recommendedAt: "周末 下午",
    score: 87,
    price: "168",
    originalPrice: "320",
    shortReason: "4小时超长畅玩，好友协同破案头脑风暴",
    dishes: "专业DM剧本主持1位、4小时专属包厢1间、无限续杯特饮4杯、免费小食拼盘1份",
    tags: ["室内轰趴", "头脑风暴", "雨天室内", "多人狂欢"],
    reasons: ["适合4人好友周末半天深度娱乐", "室内活动不受天气影响", "有效增进好友互动默契"],
    reasonItems: [
      { label: "沉浸", title: "专业主持带本", desc: "百款进阶情感/硬核本任选，新手友好。" },
      { label: "时长", title: "4小时包厢畅玩", desc: "整个下午无打扰沉浸式欢聚。" },
    ],
    notices: ["需提前1天电话预约房间与剧本分类"],
    note: "小李和李雷都很喜欢推理解谜，强烈推荐打硬核推理本。",
  }),
  makeCoupon({
    id: "c_camping_001",
    title: "山谷林间精致露营天幕下午茶双人体验",
    venue: "觅野·山谷露营地",
    type: "露营",
    category: "outdoor",
    people: "2人",
    platform: "美团",
    expireOffsetDays: 15,
    usableTime: "周六至周日 14:00-20:00",
    address: "南山大南山荔枝林生态营地",
    latitude: 22.5028,
    longitude: 113.9185,
    travelTime: "35分钟",
    recommendedAt: "晴天 周末",
    score: 88,
    price: "158",
    originalPrice: "298",
    shortReason: "晴好天气亲近自然，享受山谷微风与手冲咖啡",
    dishes: "独立天幕与蛋卷桌椅半日使用、精品手冲咖啡2杯、现烤比利时华夫饼1份、落日篝火晚会入场门票2张",
    tags: ["户外露营", "拍照打卡", "晴天必去", "自然疗愈"],
    reasons: ["远离城市喧嚣，呼吸山野清新空气", "落日与篝火拍照极其出片", "适合周末情侣或好友解压"],
    reasonItems: [
      { label: "户外", title: "山野微风", desc: "环境开阔自然，适合阳光明媚的周末午后。" },
      { label: "体验", title: "免搭营一站式", desc: "营地已备齐全部装备与咖啡小点，轻松出发。" },
    ],
    notices: ["仅限周末及节假日晴天开放，如遇雨天可顺延预约"],
    note: "建议下午16:00到达，刚好欣赏落日晚霞并参与傍晚篝火。",
  }),
  makeCoupon({
    id: "c_gym_001",
    title: "普拉提大器械私教1对1体验课1节",
    venue: "PurePilates 普拉提工作室",
    type: "瑜伽普拉提",
    category: "life",
    people: "1人",
    platform: "抖音",
    expireOffsetDays: 2,
    usableTime: "周一至周日 09:00-21:00",
    address: "科苑路金融科技大厦2层",
    latitude: 22.5412,
    longitude: 113.9482,
    travelTime: "10分钟",
    recommendedAt: "后天 上午",
    score: 84,
    price: "68",
    originalPrice: "280",
    shortReason: "2天后过期！1对1私教核心塑形，缓解久坐疲劳",
    dishes: "全身体态评估1次、核心塑形Reformer大器械私教50分钟、运动电解质饮品1瓶",
    tags: ["体态纠正", "久坐救星", "临期急用", "1对1私教"],
    reasons: ["2天后即将过期，急需排定使用", "距离近（10分钟），适合工作日下班或午休", "针对久坐肩颈酸痛针对性拉伸"],
    reasonItems: [
      { label: "临期", title: "2天后过期", desc: "高额优惠即将失效，建议尽早锁定课时。" },
      { label: "健康", title: "缓解肩颈酸痛", desc: "大器械辅助安全拉伸，快速恢复体态活力。" },
    ],
    notices: ["需自备防滑瑜伽袜，需提前1天预约教练时段"],
    note: "工作日中午或晚间均可约课，上课前需提前10分钟到店更衣。",
  }),
  makeCoupon({
    id: "c_tea_001",
    title: "新中式围炉煮茶双人雅集",
    venue: "隐溪·新中式茶空间",
    type: "咖啡甜品",
    category: "drink",
    people: "2人",
    platform: "大众点评",
    expireOffsetDays: 8,
    usableTime: "周一至周日 13:00-22:00",
    address: "南头古城春景街12号院",
    latitude: 22.5398,
    longitude: 113.9142,
    travelTime: "25分钟",
    recommendedAt: "近期 下午",
    score: 86,
    price: "78",
    originalPrice: "138",
    shortReason: "古城庭院慢煮清茶，烤物飘香，好友畅谈慢时光",
    dishes: "慢煨陈皮白茶/金骏眉1壶（可续水）、炭烤软糯年糕4块、烤脆柿2个、坚果桂花糕拼盘1份",
    tags: ["围炉煮茶", "新中式", "古城漫步", "好友畅谈"],
    reasons: ["庭院环境清幽，适合2人慢节奏交流", "秋冬温热炭火氛围感拉满", "核销时段宽裕，无需抢号"],
    reasonItems: [
      { label: "氛围", title: "庭院茶叙", desc: "红泥小火炉慢煮清茶，拍照与聊谈两相宜。" },
    ],
    notices: ["包厢需另付茶位费，大厅散座直接可用"],
    note: "推荐搭配陈皮老白茶，越煮越香醇润喉。",
  }),
  makeCoupon({
    id: "c_hotpot_exp_002",
    title: "老成都牛油九宫格老火锅双人餐",
    venue: "巴蜀记忆·九宫格火锅",
    type: "火锅",
    category: "food",
    people: "2人",
    platform: "大众点评",
    expireOffsetDays: -12,
    statusCode: "expired",
    stateClass: "expired",
    usableTime: "周一至周日 11:00-23:00",
    address: "东门步行街金海燕大厦2层",
    latitude: 22.5512,
    longitude: 114.1215,
    travelTime: "30分钟",
    score: 30,
    price: "138",
    originalPrice: "258",
    shortReason: "已过期12天，可通过快捷延期恢复使用",
    dishes: "正宗牛油锅底1份、屠场鲜毛肚1份、大刀鲜腰片1份、极品千层肚1份、手工贡菜丸子1份、红糖糍粑1份",
    tags: ["已过期", "正宗川味", "重度麻辣"],
    reasons: ["已过期，支持一键快捷延期"],
    notices: ["已过有效使用期，需快捷延期后方可使用"],
    note: "微辣也比较辣，不能吃辣可点鸳鸯锅底。",
  }),

  makeCoupon({
    id: "c_hotpot_001",
    title: "涮羊肉双人套餐",
    venue: "青禾铜锅",
    type: "火锅",
    category: "food",
    reservationRequired: true,
    expireOffsetDays: 3,
    usableTime: "周一至周日 17:00-22:00",
    address: "望京SOHO地下1层",
    latitude: 39.9982,
    longitude: 116.4812,
    travelTime: "28分钟",
    recommendedAt: "今晚 18:30",
    score: 92,
    price: "168",
    originalPrice: "288",
    shortReason: "快过期，小雨天气适合室内热食",
    dishes: "手切鲜羊肉1盘、精品肥牛1盘、鲜墨鱼滑1盘、蔬菜拼盘1份、手擀面1份、特色麻酱小料2位",
    tags: ["雨天适合", "冬天适合", "味道大", "需要洗澡洗头", "需要预约"],
    reasons: ["你和朋友今晚都有空", "天气偏凉，适合热乎的晚饭", "饭后还有足够清洁和休息时间"],
    reasonItems: [
      { label: "时间", title: "今晚空档完整", desc: "晚饭、返程和洗澡洗头都能放进节奏里。" },
      { label: "天气", title: "小雨加分", desc: "室内热食比户外项目更舒服，出门成本可控。" },
      { label: "临期", title: "3天后过期", desc: "优先处理，避免最后一天被会议或天气卡住。" },
    ],
    notices: ["建议不要安排在早会前一晚", "需要提前预约"],
    note: "小王不吃辣，建议点鸳鸯锅；周末晚市人多，最好提前电话预留位置。",
    cleanup: "饭后预留 45 分钟洗澡洗头",
  }),
  makeCoupon({
    id: "c_noodle_001",
    title: "牛肉面单人套餐",
    venue: "巷口牛肉面",
    type: "粉面",
    category: "food",
    people: "1人",
    platform: "大众点评",
    expireOffsetDays: 1,
    usableTime: "11:00-20:30",
    address: "阜通东大街6号院",
    latitude: 39.9925,
    longitude: 116.4795,
    travelTime: "12分钟",
    recommendedAt: "明天午饭",
    score: 86,
    price: "29",
    originalPrice: "48",
    shortReason: "午饭可快速解决，不太影响日程",
    dishes: "招牌红烧牛肉面1碗、爽口酸萝卜1份、凉拌海带丝1份、冰镇酸梅汤1杯",
    tags: ["快速", "适合午餐", "工作日适合"],
    reasons: ["距离近，午休时间可控", "临近过期，优先级高", "不需要额外清洁时间"],
    reasonItems: [
      { label: "效率", title: "午休可完成", desc: "单程 12 分钟，吃完还能留出缓冲。" },
      { label: "临期", title: "明天过期", desc: "适合今天或明天中午顺手解决。" },
      { label: "清洁", title: "负担很低", desc: "不会影响下午会议和晚上的生活节奏。" },
    ],
    notices: ["如果下午有会，建议提前 15 分钟出发"],
    note: "适合一个人快速解决。",
  }),
  makeCoupon({
    id: "c_museum_001",
    title: "城市博物馆双人票",
    venue: "城市博物馆",
    type: "展览",
    category: "play",
    platform: "抖音",
    expireOffsetDays: 16,
    usableTime: "周二至周日 10:00-17:00",
    address: "北辰东路15号",
    latitude: 39.9912,
    longitude: 116.3985,
    travelTime: "34分钟",
    recommendedAt: "周六 14:00",
    score: 78,
    price: "96",
    originalPrice: "160",
    shortReason: "雨天适合室内活动，时间比较宽松",
    dishes: "常设展览双人门票、特展参观资质、专业语音导览服务2份、限量版纪念明信片2张",
    tags: ["室内", "雨天适合", "适合周末"],
    reasons: ["周末下午更从容", "雨天不用担心户外体验变差", "结束后还适合顺路吃饭"],
    reasonItems: [
      { label: "天气", title: "雨天友好", desc: "室内活动稳定，不容易被天气打断。" },
      { label: "时间", title: "周末下午更松", desc: "可以慢慢看展，也方便之后顺路吃饭。" },
      { label: "路程", title: "34分钟可接受", desc: "不算近，但适合当作半日活动安排。" },
    ],
    notices: ["记得带伞", "闭馆前 1 小时停止入场"],
    note: "可以和晚饭安排在同一天。",
  }),
  makeCoupon({
    id: "c_park_001",
    title: "湖边公园游船票",
    venue: "青湖公园",
    type: "户外",
    category: "outdoor",
    expireOffsetDays: 22,
    usableTime: "09:00-18:00",
    address: "朝阳公园南路1号",
    latitude: 39.9328,
    longitude: 116.4789,
    travelTime: "42分钟",
    recommendedAt: "晴天周末上午",
    score: 61,
    price: "88",
    originalPrice: "120",
    state: "观察",
    stateClass: "watch",
    shortReason: "需要晴天，今天不适合户外",
    dishes: "双人脚踏游船体验1小时、安全救生衣2件、游湖导览手册1份",
    tags: ["户外", "晴天适合", "需防晒"],
    reasons: ["晴天体验更好", "适合和朋友留出半天", "目前还不临期"],
    reasonItems: [
      { label: "天气", title: "等晴天再去", desc: "今天有雨，游船和散步体验都会打折。" },
      { label: "时间", title: "适合半日安排", desc: "路程偏长，最好和朋友留出完整上午或下午。" },
      { label: "风险", title: "暂不临期", desc: "可以继续观察天气，不需要今天硬排。" },
    ],
    notices: ["雨天不建议安排", "晴天要记得防晒"],
    note: "需要看天气，晴天体验更好。",
    cleanup: "户外后可预留 30 分钟整理时间",
  }),
  makeCoupon({
    id: "c_coffee_001",
    title: "猫咪下午茶双人套餐",
    venue: "咪呜咖啡馆",
    type: "咖啡甜品",
    category: "drink",
    platform: "大众点评",
    expireOffsetDays: 5,
    usableTime: "13:00-18:00",
    address: "大山子南里商业街中段8号",
    latitude: 39.9885,
    longitude: 116.4952,
    travelTime: "18分钟",
    recommendedAt: "周四 下午",
    score: 85,
    price: "39",
    originalPrice: "88",
    shortReason: "适合雨天，下午时间空余",
    dishes: "猫爪拉花拿铁/美式任选2杯、经典焦糖提拉米苏1份、逗猫棒互动体验",
    tags: ["室内", "雨天适合", "轻量", "适合下午"],
    reasons: ["雨天在室内逗猫喝咖啡很舒服", "下午有足够空余时段"],
    reasonItems: [
      { label: "天气", title: "雨天友好", desc: "室内活动不受下雨打扰。" },
      { label: "时段", title: "下午茶时段", desc: "18分钟路程，适合度过悠闲下午。" },
    ],
    notices: ["馆内有猫咪，猫毛过敏者需注意"],
    note: "猫咪很可爱，免费提供猫棒。",
  }),
  makeCoupon({
    id: "c_spa_001",
    title: "泰式精油全身SPA 60分钟",
    venue: "悦然泰SPA会馆",
    type: "按摩SPA",
    category: "life",
    people: "1人",
    reservationRequired: true,
    expireOffsetDays: 8,
    usableTime: "11:00-22:00",
    address: "建国路93号万达广场写字楼B座302",
    latitude: 39.9085,
    longitude: 116.4735,
    travelTime: "20分钟",
    recommendedAt: "周五 晚上",
    score: 88,
    price: "138",
    originalPrice: "298",
    shortReason: "工作日放松，舒缓肩颈疲劳",
    dishes: "全身精油芳香SPA 60分钟、定制养生花茶1位、新鲜水果拼盘1份",
    tags: ["室内", "需要预约", "放松解压"],
    reasons: ["久坐办公后舒缓肩颈", "晚上安排不影响白天节奏"],
    reasonItems: [
      { label: "解压", title: "全身舒缓", desc: "60分钟专业泰式精油，有效缓解疲劳。" },
    ],
    notices: ["需提前至少2小时电话预约"],
    note: "适合下班后独自去放松。",
  }),
  makeCoupon({
    id: "c_movie_001",
    title: "杜比全景声电影双人通兑券",
    venue: "星光国际影城",
    type: "电影",
    category: "play",
    expireOffsetDays: -3,
    usableTime: "全天可用",
    address: "朝阳门外大街万象城5楼",
    latitude: 39.9235,
    longitude: 116.4428,
    travelTime: "15分钟",
    recommendedAt: "已过期",
    score: 30,
    price: "58",
    originalPrice: "120",
    statusCode: "expired",
    shortReason: "该券已过有效期",
    dishes: "2D/3D通兑电影票2张、双人爆米花可乐套餐1份",
    tags: ["室内", "电影"],
    notices: ["已过有效期，无法使用"],
    note: "下次记得在过期前排进日程哦。",
  }),
  makeCoupon({
    id: "c_bbq_001",
    title: "日式炭火烧肉放题双人餐",
    venue: "野原炭火烧肉",
    type: "烤肉",
    category: "food",
    platform: "大众点评",
    reservationRequired: true,
    expireOffsetDays: -6,
    usableTime: "11:30-21:30",
    address: "朝阳区霄云路日式风情美食街28号",
    latitude: 39.9520,
    longitude: 116.4680,
    travelTime: "25分钟",
    recommendedAt: "已过期",
    score: 25,
    price: "198",
    originalPrice: "368",
    statusCode: "expired",
    shortReason: "该券已过有效期",
    dishes: "极佳级雪花牛肉、厚切牛舌、黑猪五花、日式大福甜点",
    tags: ["室内", "烤肉", "味道大"],
    notices: ["已过有效期"],
    note: "已过期。",
    cleanup: "饭后预留洗澡换衣时间",
  }),
  makeCoupon({
    id: "c_bread_001",
    title: "手作法式烘焙甜点礼盒",
    venue: "莫奈法式西点",
    type: "咖啡甜品",
    category: "drink",
    people: "1人",
    platform: "抖音",
    expireOffsetDays: -10,
    usableTime: "10:00-21:00",
    address: "朝阳区青年路大悦城商业街1楼",
    latitude: 39.9210,
    longitude: 116.5180,
    travelTime: "10分钟",
    recommendedAt: "已完成",
    score: 95,
    price: "45",
    originalPrice: "88",
    statusCode: "used",
    shortReason: "已打卡兑换",
    dishes: "法式可颂2个、生巧熔岩蛋糕1块、伯爵红茶1杯",
    tags: ["甜品", "轻量"],
    notices: ["已于上周完成核销"],
    note: "体验极佳，面包口感很棒。",
  }),
];

const weather = {
  key: "partly_cloudy_day",
  title: "晴间多云",
  desc: "微风拂面，温度适宜，适合出行与大部分用券项目。",
  temperature: "22-28°",
  tips: ["防晒", "适合出行", "顺路优先"],
};

const avoid = {
  title: "城郊烧烤双人券",
  desc: "路程偏长且即将到期，建议提前规划合适时段。",
};

const plans = [
  {
    id: "p_noodle_001",
    sourceId: "c_noodle_001",
    couponId: "c_noodle_001",
    selectedTime: {
      date: dateAfter(1),
      weekday: weekdayAfter(1),
      startTime: "12:10",
      endTime: "13:10",
      scene: "午餐",
      label: monthDayWeekAfter(1),
    },
    date: monthDayWeekAfter(1),
    time: "12:10",
    title: "牛肉面单人套餐",
    venue: "巷口牛肉面",
    withText: "自己",
    travelTime: "12分钟",
    status: "已确认",
    statusCode: "confirmed",
    statusClass: "confirmed",
    note: "午饭快进快出，下午日程不受影响。",
    reminders: ["出发前 20 分钟提醒", "过期前 1 天提醒"],
  },
  {
    id: "p_museum_001",
    sourceId: "c_museum_001",
    couponId: "c_museum_001",
    selectedTime: {
      date: dateAfter(4),
      weekday: weekdayAfter(4),
      startTime: "14:00",
      endTime: "16:30",
      scene: "下午",
      label: monthDayWeekAfter(4),
    },
    date: monthDayWeekAfter(4),
    time: "14:00",
    title: "城市博物馆双人票",
    venue: "城市博物馆",
    withText: "小王",
    travelTime: "34分钟",
    status: "待确认",
    statusCode: "pending",
    statusClass: "pending",
    note: "雨天室内活动，出门前提醒带伞。",
    reminders: ["等待小王确认", "出门前查看天气", "记得带伞"],
  },
  {
    id: "p_bread_001",
    sourceId: "c_bread_001",
    couponId: "c_bread_001",
    selectedTime: {
      date: "2026-08-17",
      weekday: "周一",
      startTime: "12:30",
      endTime: "13:30",
      scene: "午餐",
      label: "8月17日 (周一)",
    },
    date: "8月17日",
    time: "12:30",
    title: "手作法式烘焙甜点礼盒",
    venue: "莫奈法式西点",
    withText: "自己",
    travelTime: "10分钟",
    status: "已完成",
    statusCode: "completed",
    statusClass: "completed",
    note: "体验极佳，面包口感很棒。",
    reminders: [],
    feedback: {
      rating: 5,
      comment: "体验极佳，面包口感很棒。",
    },
  },
  {
    id: "p_bbq_cancelled",
    sourceId: "c_bbq_001",
    couponId: "c_bbq_001",
    selectedTime: {
      date: "2026-08-10",
      weekday: "周一",
      startTime: "19:00",
      endTime: "21:00",
      scene: "晚餐",
      label: "8月10日 (周一)",
    },
    date: "8月10日",
    time: "19:00",
    title: "城郊露营烧烤双人餐",
    venue: "野趣星空营地",
    withText: "小李",
    travelTime: "45分钟",
    status: "已取消",
    statusCode: "cancelled",
    statusClass: "cancelled",
    note: "因当天突降暴雨，已协商取消。",
    reminders: [],
  },
];

const preferences = {
  food: ["不吃内脏", "少辣", "不想排长队"],
  time: ["工作日前夜不太晚", "22:00 后不出门", "周末上午尽量空出来"],
  cleanup: ["火锅后洗澡洗头", "烧烤后换衣服", "户外后预留整理时间"],
  travel: ["单程尽量 35 分钟内", "优先地铁直达", "雨天少步行"],
  limits: [
    { label: "单程上限", value: "45分钟" },
    { label: "雨天出门", value: "可以，但不想走太远" },
    { label: "晚饭时长", value: "最多 2.5 小时" },
  ],
};

const friends = [
  {
    name: "小王",
    status: "已共享可约时间",
    slots: ["周三 18:00-21:00", "周五 18:30-22:00", "周六 13:00-18:00"],
    restrictions: ["不吃辣"],
    travel: "单程不超过 40 分钟",
  },
  {
    name: "小李",
    status: "可继续完善",
    slots: ["周五 19:00 后", "周日 12:00-17:00"],
    restrictions: ["不吃内脏"],
    travel: "单程不超过 45 分钟",
  },
];

const typeOptions = ["火锅", "烧烤", "粉面", "咖啡甜品", "展览", "公园", "温泉", "其他"];
const platformOptions = ["美团", "抖音", "大众点评", "小程序", "其他"];
const reservationOptions = ["不需要", "需要", "待补充"];
const lifeTagOptions = [
  "味道大", "需要洗澡洗头", "雨天适合", "晴天适合", "冬天适合", "夏天适合",
  "适合周末", "适合工作日", "适合晚上", "适合午餐", "快速", "室内", "户外",
  "需防晒", "不适合工作日前夜", "需要预约", "适合多人", "近地铁",
];

const typeDefaults = {
  火锅: { category: "food", tags: ["味道大", "需要洗澡洗头", "雨天适合", "冬天适合", "适合晚上"], cleanup: "饭后预留 45 分钟洗澡洗头" },
  烧烤: { category: "food", tags: ["味道大", "需要洗澡洗头", "夏天适合", "适合晚上"], cleanup: "饭后预留 45 分钟洗澡洗头" },
  粉面: { category: "food", tags: ["快速", "适合午餐", "工作日适合"], cleanup: "无需额外清洁时间" },
  咖啡甜品: { category: "drink", tags: ["轻量", "适合下午", "可顺路"], cleanup: "无需额外清洁时间" },
  展览: { category: "play", tags: ["室内", "雨天适合", "适合周末"], cleanup: "无需额外清洁时间" },
  公园: { category: "outdoor", tags: ["户外", "晴天适合", "需防晒"], cleanup: "户外后可预留 30 分钟整理时间" },
  温泉: { category: "life", tags: ["冬天适合", "需预留时间", "适合周末"], cleanup: "自带清洁时间，但需要更长行程" },
  其他: { category: "other", tags: ["待判断"], cleanup: "按实际情况预留时间" },
};

module.exports = {
  coupons, weather, avoid, plans, preferences, friends,
  typeOptions, platformOptions, reservationOptions, lifeTagOptions, typeDefaults,
};
