const normalizer = require("./plan/planNormalizer.js");
const riskEvaluator = require("./plan/planRiskEvaluator.js");
const part1 = require("./planStoreCore.js");
const part2 = require("./planStoreTransaction.js");
const part3 = require("./planStoreBuilders.js");
const part4 = require("./planStoreLifecycle.js");
const part5 = require("./planStoreCollaboration.js");

const parts = Object.assign({}, part1, part2, part3, part4, part5);
const {
  VALID_TRANSITIONS,
  VALID_STATUS_CODES,
  asValidStatusCode,
  canTransitionPlanStatus,
  getPlans,
  getStoredPlans,
  saveStoredPlans,
  findPlan,
  findStoredPlan,
  getPlanById,
  getPlan,
  createPlan,
  restoreCouponSnapshots,
  bulkUpsertPlans,
  upsertStoredPlan,
  savePlan,
  buildPlanFromRecommendation,
  createPlanFromRecommendation,
  restorePlanSnapshot,
  removeTemporaryDirectUsePlan,
  removeImportedPlan,
  createManualPlanFromSpin,
  updatePlan,
  updatePlanStatus,
  completePlan,
  cancelPlan,
  reschedulePlan,
  updateReservationStatus,
  markFriendConfirmed,
  markFriendRejected,
  attachInvite,
  updateFeedback,
} = parts;

module.exports = {
  STATUS_META: normalizer.STATUS_META,
  STATUS_ALIAS_MAP: normalizer.STATUS_ALIAS_MAP,
  VALID_TRANSITIONS,
  canTransitionPlanStatus,
  normalizeStatus: normalizer.normalizeStatus,
  statusLabel: normalizer.statusLabel,
  statusClass: normalizer.statusClass,
  buildLocationFromCoupon: normalizer.buildLocationFromCoupon,
  selectedTimeFromLegacy: normalizer.selectedTimeFromLegacy,
  normalizePlan: normalizer.normalizePlan,
  parsePlanStart: normalizer.parsePlanStart,
  validatePlan: riskEvaluator.validatePlan,
  applyRisk: riskEvaluator.applyRisk,
  getStoredPlans,
  saveStoredPlans,
  getPlans,
  findPlan,
  getPlan,
  getPlanById,
  createPlan,
  bulkUpsertPlans,
  upsertStoredPlan,
  savePlan,
  buildPlanFromRecommendation,
  createPlanFromRecommendation,
  removeTemporaryDirectUsePlan,
  removeImportedPlan,
  createManualPlanFromSpin,
  updatePlan,
  updatePlanStatus,
  completePlan,
  cancelPlan,
  reschedulePlan,
  updateReservationStatus,
  markFriendConfirmed,
  markFriendRejected,
  attachInvite,
  updateFeedback,
};
